- package-lock.json
- package.json
> Adds nodemon and adds dev script

- README.md
- app/commands/daily.js
- app/index.js
- app/utils/prepareAnswer.js
Fixes #13 
@gurrrung Let me know if you need any changes :)
> Adds `daily n` feature

- app/commands/testingCentres.js
- app/index.js
- app/utils/prepareAnswer.js
Uses the resources API to try to address #10 and #18
> add `test state` feature

- app/utils/prepareAnswer.js
The result will now display with the Indian number format (10,00,000 instead of 1,000,000)
> Replaced comma in numbers format to Indian format

- app/commands/stateName.js
- app/utils/prepareAnswer.js
with reference to the issue #23
> Added no of tests stat when displaying 'state' data

- app/commands/testingCentres.js
- app/utils/prepareAnswer.js
closes #38 and closes #39 
for #39, resources will be shown in two separate messages to counter 
`Unhandled rejection Error: ETELEGRAM: 400 Bad Request: message is too long` if message length is greater than the limit.
> Fix resource data(#38,#39)

- app/commands/testingCentres.js
- app/utils/prepareAnswer.js
> Refactor for `for in` line 79

- app/commands/testingCentres.js
- app/utils/prepareAnswer.js
> Refactor for `next line max len`(point 2 #41)

- app/commands/testingCentres.js
- app/utils/prepareAnswer.js
> Add `total new cases` (#46)

- app/index.js
> added `_` support

- app/commands/dailyActive.js
- app/index.js
- app/utils/prepareAnswer.js
> added `daily active` command

- app/utils/prepareAnswer.js
> fixed negative numbers comma

- README.md
- app/commands/dailyGraph.js
- app/commands/testingCentres.js
- app/index.js
- app/utils/prepareAnswer.js
> Graph for daily new cases

- README.md
- app/commands/dailyRecovered.js
- app/index.js
- app/utils/prepareAnswer.js
closes #53 
todo: support the `daily rec N` command.
> added daily rec command

- README.md
- app/commands/dailyDeceased.js
- app/commands/testingCentres.js
- app/index.js
- app/utils/prepareAnswer.js
> added `daily dec N` command

- README.md
- app/commands/graph.js
- app/commands/testingCentres.js
- app/index.js
- app/utils/prepareAnswer.js
> added `graph` command

- README.md
- app/commands/dailyDeceasedGraph.js
- app/commands/testingCentres.js
- app/index.js
- app/utils/prepareAnswer.js
> graph support for `daily dec N`

- app/commands/testingCentres.js
- app/utils/prepareAnswer.js
> Added graph title

- app/commands/graph.js
- app/commands/testingCentres.js
- app/utils/prepareAnswer.js
- package-lock.json
- package.json
For #81 
`graph 180` working 🎉
> added url shortener

- app/commands/dailyActiveGraph.js
- app/commands/dailyDeceasedGraph.js
- app/commands/dailyGraph.js
- app/commands/dailyRecoveredGraph.js
- app/commands/testingCentres.js
- app/utils/prepareAnswer.js
> added url shortener for all graph commands

- README.md
> Add android screenshots

- app/utils/prepareAnswer.js
> fixed date in daily command
